```{r load-packages}
library(DiagrammeR)
library(magrittr)
library(tidyr)
library(SpaDES)
```

```{r gantt-chart}
DiagrammeR("
        gantt
        dateFormat  YYYY-MM-DD
        title A Very Nice Gantt Diagram

        section Basic Tasks
        This is completed             :done,          first_1,    2014-01-06, 2014-01-08
        This is active                :active,        first_2,    2014-01-09, 3d
        Do this later                 :               first_3,    after first_2, 5d
        Do this after that            :               first_4,    after first_3, 5d

        section Important Things
        Completed, critical task      :crit, done,    import_1,   2014-01-06,24h
        Also done, also critical      :crit, done,    import_2,   after import_1, 2d
        Doing this important task now :crit, active,  import_3,   after import_2, 3d
        Next critical task            :crit,          import_4,   after import_3, 5d

        section The Extras
        First extras                  :active,        extras_1,   after import_4,  3d
        Second helping                :               extras_2,   after extras_1, 20h
        More of the extras            :               extras_3,   after extras_1, 48h
")
```

```{r gantt-chart-df}
df <- data.frame(task = c("task1", "task2", "task3"),
                 status = c("done", "active", "crit"),
                 pos = c("first_1", "first_2", "first_3"),
                 start = c("2014-01-06", "2014-01-09", "after first_2"),
                 end = c("2014-01-08", "3d", "5d"))
mermaid(
  paste0(
    # mermaid "header", each component separated with "\n" (line break)
    "gantt", "\n",
    "dateFormat  YYYY-MM-DD", "\n",
    "title A Very Nice Gantt Diagram", "\n",
    # unite the first two columns (task & status) and separate them with ":"
    # then, unite the other columns and separate them with ","
    # this will create the required mermaid "body"
    paste(df %>%
            unite(i, task, status, sep = ":") %>%
            unite(j, i, pos, start, end, sep = ",") %>%
            .$j,
          collapse = "\n"
    ), "\n"
  )
)
```

```{r simulation, eval=TRUE}
options("spades.nCompleted" = 30)

outputPath <- file.path(tempdir(), "simOutputs")
times <- list(start=0.0, stop=100.0, timestepUnit="day")
parameters <- list(.globals=list(stackName="landscape", .outputPath=outputPath,
                                 burnStats="nPixelsBurned"),
                   .progress=list(NA),
                   randomLandscapes=list(nx=100L, ny=100L, inRAM=TRUE,
                                         .plotInitialTime=NA, .plotInterval=NA),
                   fireSpread=list(nFires=10L, spreadprob=0.225, its=1e6,
                                   persistprob=0, returnInterval=10, startTime=0,
                                  .plotInitialTime=NA, .plotInterval=NA),
                   caribouMovement=list(N=100L, moveInterval=1,
                                        .plotInitialTime=NA, .plotInterval=NA))
modules <- list("randomLandscapes", "fireSpread", "caribouMovement")
objects <- list()
path <- system.file("sampleModules", package="SpaDES")

mySim <- simInit(times=times, params=parameters, modules=modules,
                 objects=objects, path=path)

simEvents(mySim)
mySim <- spades(mySim)
simCompleted(mySim)
```

```{r gantt-chart-sim, eval=TRUE}
sim2gantt <- function(sim) {
  dt <- simCompleted(sim)
  start <- "2015-01-01"
  ts <- simTimestepUnit(sim)
  denom <- as.numeric(dday(1))
  mult <- if (ts=="second") {
    as.numeric(dsecond(1)) / denom
  } else if (ts=="hour") {
    as.numeric(dhour(1)) / denom
  } else if (ts=="day") {
    as.numeric(dday(1)) / denom
  } else if (ts=="week") {
    as.numeric(dweek(1)) / denom
  } else if (ts=="month") {
    as.numeric(dmonth(1)) / denom
  } else if (ts=="year") {
    as.numeric(dyear(1)) / denom
  }
  out <- lapply(unique(dt$moduleName), function(x) {
    data.frame(task = dt[moduleName==x]$eventType,
                   status = rep("active", nrow(dt[moduleName==x])),
                   pos = paste0(x, 1:nrow(dt[moduleName==x])),
                   start = as.Date(dt[moduleName==x]$eventTime * mult, origin=start),
                   end = paste0((dt[moduleName==x]$eventTime + 7)*mult, strtrim(ts, 1)))
  })
  names(out) <- unique(dt$moduleName)
  return(out)
}

ll <- sim2gantt(mySim)

mermaid(
  paste0(
    # mermaid "header", each component separated with "\n" (line break)
    "gantt", "\n",
    "dateFormat  YYYY-MM-DD", "\n",
    "title SPaDES simulation diagram", "\n",
    # unite the first two columns (task & status) and separate them with ":"
    # then, unite the other columns and separate them with ","
    # this will create the required mermaid "body"
    paste("section ", names(ll), "\n", lapply(ll, function(df) {
      paste(df %>%
              unite(i, task, status, sep = ":") %>%
              unite(j, i, pos, start, end, sep = ",") %>%
              .$j,
            collapse = "\n")
      }), collapse = "\n"), "\n"
  )
)
```
