```{r load-packages, echo=FALSE, message=FALSE, warning=FALSE}
devtools::dev_mode(TRUE)
library(DiagrammeR)
library(SpaDES)
```

```{r sequence-diagram, eval=FALSE, echo=FALSE}
mermaid("
sequenceDiagram
  customer->>ticket seller: ask ticket
  ticket seller->>database: seats
  alt tickets available
    database->>ticket seller: ok
    ticket seller->>customer: confirm
    customer->>ticket seller: ok
    ticket seller->>database: book a seat
    ticket seller->>printer: print ticket
  else sold out
    database->>ticket seller: none left
    ticket seller->>customer: sorry
  end
")
```

```{r simulation, eval=TRUE, message=FALSE, warning=FALSE}
outputPath <- file.path(tempdir(), "simOutputs")
times <- list(start=0.0, stop=3, timestepUnit="year")
parameters <- list(.globals=list(stackName="landscape", burnStats="nPixelsBurned"),
                   .progress=list(NA),
                   randomLandscapes=list(nx=100L, ny=100L, inRAM=TRUE,
                                         .plotInitialTime=NA, .plotInterval=NA),
                   fireSpread=list(nFires=10L, spreadprob=0.225, its=1e6,
                                   persistprob=0, returnInterval=10, startTime=0,
                                  .plotInitialTime=NA, .plotInterval=NA),
                   caribouMovement=list(N=100L, moveInterval=1,
                                        .plotInitialTime=NA, .plotInterval=NA))
modules <- list("randomLandscapes", "fireSpread", "caribouMovement")
objects <- list()
path <- system.file("sampleModules", package="SpaDES")

mySim <- simInit(times=times, params=parameters, modules=modules, objects=objects, path=path)

#simEvents(mySim)
mySim <- spades(mySim)
#simCompleted(mySim)
```

```{r sequence-diagram-sim, eval=TRUE, fig.height=8, fig.width=10}
objectDiagram(mySim)
```

Compare with `moduleDiagram`:

```{r module-diagram-sim, eval=TRUE}
moduleDiagram(mySim)
```

