
```{r load_data, cache=TRUE}
library(SpaDES)
rasterOptions(maxmemory=2e9)
downloadRequired = FALSE
interactiveExtent = FALSE

setwd("~")
dir.create("spadesTmp")
setwd(file.path("spadesTmp"))

if(downloadRequired) {

  #46MB file
  fN <- "lcc05.zip"
  download.file("ftp://ftp.ccrs.nrcan.gc.ca/ad/NLCCLandCover/LandcoverCanada2005_250m/LandCoverOfCanada2005_V1_4.zip", fN, mode="wb")
  unzip(fN, files="LCC2005_V1_4a.tif")
  
  # 9MB file
  download.file("ftp://ftp.daac.ornl.gov/data/nacp/NA_TreeAge//data/can_age04_1km.tif",
                "age.tif",mode="wb")
}


fileList <- data.frame(files=c("LCC2005_V1_4a.tif",
                               "age.tif"),
                       functions="raster", packages="raster",
                       objectNames=c("lcc05","age"),
                       stringsAsFactors=FALSE)
loadFiles(fileList=fileList)
#ext <- extent(-1380607, -345446, 7211410, 7971750) # large central BC 12Million
ext <- extent(-1073154,-987285,7438423,7512480) # small central Sask 100 Thousand

if(interactiveExtent) {
  dev(4)
  plot(lcc05)
  ext <- drawExtent()
}
vegMapLcc <- crop(lcc05,ext)
if(ncell(vegMapLcc)>1e6) beginCluster(10)
# age will not run with projectRaster directly. Instead, project the vegMap to age, then crop, then project back to vegMap
vegMapLcc.crsAge = projectRaster(vegMapLcc, crs=crs(age))
age.crsAge <- crop(age, vegMapLcc.crsAge)
ageMap <- projectRaster(age.crsAge, to=vegMapLcc, method="ngb")

endCluster()
                                   
writeRaster(ageMap, filename="ageMap.tif", overwrite=TRUE)
```


```{r reclassify, cache=TRUE}
  ### From the table 1 in Word file from Steve Cumming & Pierre Vernier, June 6, 2014
  ###  09 A5 MDR ANslysis V4_SL.docx
  #
  # lcc05TrajReclass <- read.table(file="clipboard", header=TRUE, sep="\t")
  # dput(lcc05TrajReclass[,c("LCC05.classes","Trajectory","Description")])
  # dput(lcc05TrajReclass[,c("LCC05.classes","VEG.reclass","Description")])
  #

  lcc05TrajReclass <- structure(
    list(LCC05.classes=structure(c(2L, 11L, 8L, 6L, 3L, 4L, 9L, 5L, 10L, 7L, 1L),
                                 .Label=c("0,30,31,32,33,36,38,39", "1",
                                          "16,35", "17,18,20,21,22,23,24,25",
                                          "19", "2,11,12", "26,27,28,29",
                                          "3,4,5,13,14,15", "34", "37",
                                          "6,7,8,9,10"), class = "factor"),
         Trajectory=structure(c(2L, 5L, 7L, 6L, 8L, 9L, 1L, 10L, 11L, 3L, 4L),
                                .Label=c("1,2,3,4,5,6", "1,3,4,5,6", "10",
                                         "11", "2,4", "3,4,5", "3,4,6", "6",
                                         "6", "8", "9"), class = "factor"),
         Description=structure(c(2L, 7L, 6L, 4L, 9L, 5L, 1L, 11L, 10L, 3L, 8L),
                               .Label=c("Burned", "Closed coniferous", "Cropland",
                                        "Deciduous", "Herbaceous", "Mixedwood",
                                        "Open coniferous", "Other", "Shrub",
                                        "Water", "Wetland"), class = "factor")),
    .Names=c("LCC05.classes", "Trajectory", "Description"),
    class="data.frame", row.names = c(NA, -11L))


  lcc05VegReclass <- structure(
    list(LCC05.classes=structure(c(2L, 11L, 8L, 6L, 3L, 4L, 9L, 5L, 10L, 7L, 1L),
                                 .Label=c("0,30,31,32,33,36,38,39", "1",
                                          "16,35", "17,18,20,21,22,23,24,25",
                                          "19", "2,11,12", "26,27,28,29",
                                          "3,4,5,13,14,15", "34", "37",
                                          "6,7,8,9,10"), class = "factor"),
         VEG.reclass=1:11, Description=structure(
           c(2L, 7L, 6L, 4L, 9L, 5L, 1L, 11L, 10L, 3L, 8L),
           .Label = c("Burned", "Closed coniferous",  "Cropland", "Deciduous",
                      "Herbaceous", "Mixedwood", "Open coniferous", "Other",
                      "Shrub", "Water", "Wetland"), class = "factor")),
    .Names = c("LCC05.classes", "VEG.reclass", "Description"),
    class = "data.frame", row.names = c(NA, -11L))


  lcc05VegLabels <- as.numeric(strsplit(paste(lcc05VegReclass$LCC05.classes, collapse=","),",")[[1]])
  numLccInVeg <- sapply(strsplit(unname(sapply(as.character(lcc05VegReclass$LCC05.classes), function(x) x)), ","), length)
   lcc05VegTable <- cbind(lcc05VegLabels,rep(lcc05VegReclass$VEG.reclass,numLccInVeg))
   vegMap <- RasterLayerNamed(reclassify(vegMapLcc, lcc05VegTable),name="vegMap")
   vegMapColors <<- getColors(lcc05)[[1]][c(1,lcc05VegTable[,1][match(1:11,
                                                                 lcc05VegTable[,2])]+1)]
   setColors(vegMap, n=12 ) <- vegMapColors
  
  # the raster package does not keep colors when writing to a tif file
   writeRaster(vegMap, filename="vegMap.tif", overwrite=TRUE)

  lcc05TrajLabels <- as.numeric(strsplit(paste(lcc05TrajReclass$LCC05.classes, collapse=","), ",")[[1]])
  numLccInTraj <- sapply(strsplit(unname(sapply(as.character(lcc05TrajReclass$LCC05.classes), function(x) x)), ","), length)

  lcc05TrajReclass$TrajectoryNum <- lapply(as.character(
    lcc05TrajReclass$Trajectory), function(x) as.numeric(strsplit(x,",")[[1]]))

  lcc05TrajTable <- cbind(
    lcc05TrajLabels,
    unlist(
      lapply(1:length(lcc05TrajReclass$TrajectoryNum),
             function(x) 
               sample(lcc05TrajReclass$TrajectoryNum[[x]],
                      numLccInTraj[x],replace=T))))

#  lcc05TrajTable <- cbind(lcc05TrajLabels,rep(lcc05TrajReclass$Trajectory,numLccInTraj))
  trajMap <- reclassify(vegMapLcc, lcc05TrajTable)
  setColors(trajMap,n=12) <- brewer.pal(9, "YlGn")
  name(trajMap) <- "trajMap"

  # trajObj.raw <- read.table(file="clipboard", sep="\t", header=TRUE, stringsAsFactors=FALSE)
  # dput(trajObj.raw)
  trajObj.raw <- structure(
    list(Veg.Type=c("Closed coniferous", "Open coniferous", "Mixedwood",
                    "Deciduous*", "Deciduous*", "Shrub", "Herbaceous"),
         X0.2=c("Burned", "Burned", "Burned", "Burned", "Burned", "Burned", "Burned"),
         X3.20=c("Closed coniferous", "Open coniferous", "Deciduous",
                 "Deciduous", "Deciduous", "Shrub", "Herbaceous"),
         X21.60=c("Closed coniferous", "Open coniferous", "Mixedwood",
                  "Mixedwood", "Deciduous", "Shrub", "Herbaceous"),
         X61.80=c("Closed coniferous", "Open coniferous", "Mixedwood",
                  "Mixedwood", "Deciduous", "Mixedwood", "Herbaceous"),
         X81.120=c("Closed coniferous", "Open coniferous", "Mixedwood",
                   "Mixedwood", "Deciduous", "Mixedwood", "Herbaceous"),
         X121.160=c("Closed coniferous", "Open coniferous", "Mixedwood",
                    "Open coniferous", "Deciduous", "Closed coniferous",
                    "Herbaceous"),
         X.160=c("Closed coniferous", "Open coniferous", "Closed coniferous",
                 "Closed coniferous", "Closed coniferous", "Closed coniferous",
                 "Herbaceous")),
    .Names=c("Veg.Type", "X0.2", "X3.20", "X21.60", "X61.80", "X81.120", "X121.160", "X.160"),
    class="data.frame", row.names=c(NA, -7L))

  numYearsPer <- na.omit(unlist(lapply(strsplit(substr(colnames(trajObj.raw),2,9),"\\."), function(x) diff(as.numeric(x))))+1)
  maxAge <- 200
  ages <- 0:maxAge


  trajObj1 <- apply(trajObj.raw[-4,-c(1)],1,function(x) rep(x, times=c(numYearsPer, maxAge+1-sum(numYearsPer))))
  trajObj2 <- cbind(trajObj1,matrix(rep(c("Burned", "Wetland", "Water", "Cropland","Other"), each=maxAge+1), ncol=5))
  trajObj <<- matrix(match(trajObj2, 
                           as.character(lcc05TrajReclass$Description))
                     , ncol=ncol(trajObj2))

```

```{r prepare_simInit}
fileList <- data.frame(files=c("vegMap.tif",
                               "ageMap.tif"),
                       functions="rasterToMemory", packages="SpaDES",
                       stringsAsFactors=FALSE)

times=list(start=0.0, stop=200)
#loadFiles(fileList=fileList)
parameters <- list(.globals=list(burnStats="nPixelsBurned"),
                   .progress=list(.graphical=TRUE, .progressInterval=2),
                   .loadFileList=fileList,
                   forestSuccession=list(returnInterval=1, startTime=0,
                                   .plotInitialTime=1, .plotInterval=1),
                   forestAge=list(returnInterval=1, startTime=0.5,
                                        .plotInitialTime=1, .plotInterval=1),
                   fireSpreadLcc=list(nFires= 10, #spreadprob=0.225,
                                      its=1e6,
                                   persistprob=0, returnInterval=1, startTime=1,
                                   .plotInitialTime=1, .plotInterval=1)
#                   caribouMovement=list(N=1e2, moveInterval=1,
#                                        .plotInitialTime=1.01, .plotInterval=1)
)


modules <- list("forestSuccession", "forestAge", "fireSpreadLcc")
path <- file.path("C:","Eliot","GitHub","SpaDES","SAMPLE")
```

```{r run_spades}
mySim <- simInit(times=times, params=parameters, modules=modules, path=path)
dev(4)#pdf("test.pdf")
print(system.time(mySim <- spades(mySim, debug=F)))
#simStopTime(mySim)<-20
#dev.off()
```
