
```{r load_data, eval=TRUE, echo=TRUE}
library(dplyr)
library(raster)
library(rgdal)
library(SpaDES)

rasterOptions(maxmemory=1e9)
downloadRequired = FALSE

dataPath <- file.path("S:","McIntire","data")

setwd(dataPath)

if(downloadRequired) {

  #46MB file
  fN <- "lcc05.zip"
  download.file("ftp://ftp.ccrs.nrcan.gc.ca/ad/NLCCLandCover/LandcoverCanada2005_250m/LandCoverOfCanada2005_V1_4.zip", fN, mode="wb")
  unzip(fN, files="LCC2005_V1_4a.tif")

  # 9MB file
  download.file("ftp://ftp.daac.ornl.gov/data/nacp/NA_TreeAge//data/can_age04_1km.tif",
                "age.tif",mode="wb")

}


fileList <- data.frame(files=c("LCC2005_V1_4a.tif",
                               "age.tif"),
                       functions="raster", packages="raster",
                       objectNames=c("lcc05","age"),
                       stringsAsFactors=FALSE)
loadFiles(fileList=fileList)

# Saskatchewan
setwd("S:\\McIntire\\data\\boreal")
boreal <- readOGR(dsn=".", layer="NABoreal")
setwd("S:\\McIntire\\data")
load("CAN_adm1.RData")
canada1 = gadm
crsLcc <- crs(lcc05)
crsBoreal <- crs(boreal)
crsSask <- "+proj=aea +lat_1=47.5 +lat_2=54.5 +lat_0=0 +lon_0=-106 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0"
canadaLcc = spTransform(canada1, crsLcc)
Sask = canadaLcc[na.omit(match(c("Saskatchewan"),canadaLcc$NAME_1)),]
ext = spTransform(Sask, crs(lcc05))
#SaskPolyLcc = spTransform(Sask, crs(lcc05))
SaskPolySask <- spTransform(Sask, CRS(crsSask))
vegMapLcc <- crop(lcc05,ext)
if(ncell(vegMapLcc)>1e6) beginCluster(4)
system.time(vegMapLccSaskTmp <- projectRaster(vegMapLcc, crs=crsSask, method="ngb"))
endCluster()

vegMapLccSaskTmp@legend@colortable <-lcc05@legend@colortable
vegMapLcc <- crop(vegMapLccSaskTmp, extent(SaskPolySask))

vegMapLcc.crsAge = projectRaster(vegMapLcc, crs=crs(age), method="ngb")
age.crsAge <- crop(age, vegMapLcc.crsAge)
ageMap <- projectRaster(age.crsAge, to=vegMapLcc, method="ngb")

lcc05TrajReclass <- structure(
  list(LCC05.classes=structure(c(2L, 11L, 8L, 6L, 3L, 4L, 9L, 5L, 10L, 7L, 1L),
                               .Label=c("0,30,31,32,33,36,38,39", "1",
                                        "16,35", "17,18,20,21,22,23,24,25",
                                        "19", "2,11,12", "26,27,28,29",
                                        "3,4,5,13,14,15", "34", "37",
                                        "6,7,8,9,10"), class = "factor"),
       Trajectory=structure(c(2L, 5L, 7L, 6L, 8L, 9L, 1L, 10L, 11L, 3L, 4L),
                            .Label=c("1,2,3,4,5,6", "1,3,4,5,6", "10",
                                     "11", "2,4", "3,4,5", "3,4,6", "6",
                                     "6", "8", "9"), class = "factor"),
       Description=structure(c(2L, 7L, 6L, 4L, 9L, 5L, 1L, 11L, 10L, 3L, 8L),
                             .Label=c("Burned", "Closed coniferous", "Cropland",
                                      "Deciduous", "Herbaceous", "Mixedwood",
                                      "Open coniferous", "Other", "Shrub",
                                      "Water", "Wetland"), class = "factor")),
  .Names=c("LCC05.classes", "Trajectory", "Description"),
  class="data.frame", row.names = c(NA, -11L))


lcc05VegReclass <- structure(
  list(LCC05.classes=structure(c(2L, 11L, 8L, 6L, 3L, 4L, 9L, 5L, 10L, 7L, 1L),
                               .Label=c("0,30,31,32,33,36,38,39", "1",
                                        "16,35", "17,18,20,21,22,23,24,25",
                                        "19", "2,11,12", "26,27,28,29",
                                        "3,4,5,13,14,15", "34", "37",
                                        "6,7,8,9,10"), class = "factor"),
       VEG.reclass=1:11, Description=structure(
         c(2L, 7L, 6L, 4L, 9L, 5L, 1L, 11L, 10L, 3L, 8L),
         .Label = c("Burned", "Closed coniferous",  "Cropland", "Deciduous",
                    "Herbaceous", "Mixedwood", "Open coniferous", "Other",
                    "Shrub", "Water", "Wetland"), class = "factor")),
  .Names = c("LCC05.classes", "VEG.reclass", "Description"),
  class = "data.frame", row.names = c(NA, -11L))


lcc05VegLabels <- as.numeric(strsplit(paste(lcc05VegReclass$LCC05.classes, collapse=","),",")[[1]])
numLccInVeg <- sapply(strsplit(unname(sapply(as.character(lcc05VegReclass$LCC05.classes), function(x) x)), ","), length)
lcc05VegTable <- cbind(lcc05VegLabels,rep(lcc05VegReclass$VEG.reclass,numLccInVeg))
vegMap <- reclassify(vegMapLcc, lcc05VegTable)
vegMapColors <<- getColors(lcc05)[[1]][c(1,lcc05VegTable[,1][match(1:11,
                                                                   lcc05VegTable[,2])]+1)]
setColors(vegMap, n=12 ) <- vegMapColors

# the raster package does not keep colors when writing to a tif file

lcc05TrajLabels <- as.numeric(strsplit(paste(lcc05TrajReclass$LCC05.classes, collapse=","), ",")[[1]])
numLccInTraj <- sapply(strsplit(unname(sapply(as.character(lcc05TrajReclass$LCC05.classes), function(x) x)), ","), length)

lcc05TrajReclass$TrajectoryNum <- lapply(as.character(
  lcc05TrajReclass$Trajectory), function(x) as.numeric(strsplit(x,",")[[1]]))

lcc05TrajTable <- cbind(
  lcc05TrajLabels,
  unlist(
    lapply(1:length(lcc05TrajReclass$TrajectoryNum),
           function(x)
             sample(lcc05TrajReclass$TrajectoryNum[[x]],
                    numLccInTraj[x],replace=T))))

#  lcc05TrajTable <- cbind(lcc05TrajLabels,rep(lcc05TrajReclass$Trajectory,numLccInTraj))
trajMap <- reclassify(vegMapLcc, lcc05TrajTable)
setColors(trajMap,n=12) <- brewer.pal(9, "YlGn")
name(trajMap) <- "trajMap"

# trajObj.raw <- read.table(file="clipboard", sep="\t", header=TRUE, stringsAsFactors=FALSE)
# dput(trajObj.raw)
trajObj.raw <- structure(
  list(Veg.Type=c("Closed coniferous", "Open coniferous", "Mixedwood",
                  "Deciduous*", "Deciduous*", "Shrub", "Herbaceous"),
       X0.2=c("Burned", "Burned", "Burned", "Burned", "Burned", "Burned", "Burned"),
       X3.20=c("Closed coniferous", "Open coniferous", "Deciduous",
               "Deciduous", "Deciduous", "Shrub", "Herbaceous"),
       X21.60=c("Closed coniferous", "Open coniferous", "Mixedwood",
                "Mixedwood", "Deciduous", "Shrub", "Herbaceous"),
       X61.80=c("Closed coniferous", "Open coniferous", "Mixedwood",
                "Mixedwood", "Deciduous", "Mixedwood", "Herbaceous"),
       X81.120=c("Closed coniferous", "Open coniferous", "Mixedwood",
                 "Mixedwood", "Deciduous", "Mixedwood", "Herbaceous"),
       X121.160=c("Closed coniferous", "Open coniferous", "Mixedwood",
                  "Open coniferous", "Deciduous", "Closed coniferous",
                  "Herbaceous"),
       X.160=c("Closed coniferous", "Open coniferous", "Closed coniferous",
               "Closed coniferous", "Closed coniferous", "Closed coniferous",
               "Herbaceous")),
  .Names=c("Veg.Type", "X0.2", "X3.20", "X21.60", "X61.80", "X81.120", "X121.160", "X.160"),
  class="data.frame", row.names=c(NA, -7L))

numYearsPer <- na.omit(unlist(lapply(strsplit(substr(colnames(trajObj.raw),2,9),"\\."), function(x) diff(as.numeric(x))))+1)
maxAge <- 200
ages <- 0:maxAge


trajObj1 <- apply(trajObj.raw[-4,-c(1)],1,function(x) rep(x, times=c(numYearsPer, maxAge+1-sum(numYearsPer))))
trajObj2 <- cbind(trajObj1,matrix(rep(c("Burned", "Wetland", "Water", "Cropland","Other"), each=maxAge+1), ncol=5))
trajObj <<- matrix(match(trajObj2,
                         as.character(lcc05TrajReclass$Description))
                   , ncol=ncol(trajObj2))

ageMapInit <- ageMap
vegMapInit <- vegMap
trajMapInit <- trajMap
setColors(vegMapInit, n=12 ) <- vegMapColors

writeRaster(ageMap, filename="ageMap.tif", overwrite=TRUE, datatype="INT1U")
writeRaster(vegMap, filename="vegMap.tif", overwrite=TRUE, datatype="INT1U")
writeRaster(trajMapInit, filename="trajMap.tif", overwrite=TRUE, datatype="INT1U")
```

```{r hash, eval=TRUE, echo=TRUE}
vegMap <- raster("vegMap.tif")  
trajMap <- raster("trajMap.tif")
ageMap.wrong <- raster("ageMap.tif")


library(microbenchmark)
(mb=microbenchmark(times=1L,dplyrVersion <- {
  vegVal <- tbl_df(data.frame(traj = getValues(trajMap),
                              age=getValues(ageMap)+1,
                              rand=sample(1:15, ncell(trajMap), replace=T),
                              index=1:ncell(trajMap)))

  (a = vegVal %>%
     group_by(traj,age,rand) %>%
     mutate(label=min(index))) 

  d = a %>%
    summarise(label=unique(label)) %>%
    ungroup() %>%
    mutate(veg=trajObj[cbind(age, traj)]) %>%
    select(label, veg, age, traj, rand)

## Simulation 10 time steps on the smaller data
  for(i in 1:100) {
    d[,"age"] <- d[,"age"]+0
    d[,"veg"]=trajObj[cbind(d[,"age"], d[,"traj"])]
  }

  #vegVal2 = left_join(d,a, by="label" )
  vegVal2 = inner_join(a,d, by="label" )
  vegMap0 <- setValues(vegMap,vegVal2$veg)
  setColors(vegMap0, n=12 ) <- vegMapColors
} ,

 vectorVersion<-{
   ageMap.v <- round(getValues(ageMap))+1
   trajMap.v <- getValues(trajMap)
   vegMap.v <- trajObj[cbind(ageMap.v,trajMap.v)]

   for(i in 1:100) {
     ageMap.v <- ageMap.v + 0
     vegMap.v <- trajObj[cbind(ageMap.v, trajMap.v)]
   }

     vegMap <- raster(ageMap)
   vegMap1 <- setValues(vegMap,vegMap.v)
 setColors(vegMap1, n=12 ) <- vegMapColors
 }
 )
 )

all.equal(getValues(vegMap0), getValues(vegMap1))
```

indexRaster<-raster(trajMap)
indexRaster<-setValues(indexRaster,1:ncell(trajMap))
ind = sampleRegular(indexRaster, 3e4,asRaster=TRUE, useGDAL=TRUE)

vegVal2 = inner_join(a[getValues(ind),],d, by="label" )
smallVeg=raster(ind)
vegMap3 <- setValues(smallVeg,vegVal2$veg)
dev(4);plot(vegMap3)

