// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pointDistance2
NumericMatrix pointDistance2(NumericMatrix to, NumericMatrix from);
RcppExport SEXP SpaDES_pointDistance2(SEXP toSEXP, SEXP fromSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type from(fromSEXP);
    rcpp_result_gen = Rcpp::wrap(pointDistance2(to, from));
    return rcpp_result_gen;
END_RCPP
}
// pointDistance3
NumericMatrix pointDistance3(NumericVector fromX, NumericVector toX, NumericVector fromY, NumericVector toY, double maxDistance);
RcppExport SEXP SpaDES_pointDistance3(SEXP fromXSEXP, SEXP toXSEXP, SEXP fromYSEXP, SEXP toYSEXP, SEXP maxDistanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fromX(fromXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type toX(toXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fromY(fromYSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type toY(toYSEXP);
    Rcpp::traits::input_parameter< double >::type maxDistance(maxDistanceSEXP);
    rcpp_result_gen = Rcpp::wrap(pointDistance3(fromX, toX, fromY, toY, maxDistance));
    return rcpp_result_gen;
END_RCPP
}
// duplicatedInt
LogicalVector duplicatedInt(IntegerVector x);
RcppExport SEXP SpaDES_duplicatedInt(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(duplicatedInt(x));
    return rcpp_result_gen;
END_RCPP
}
