# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' Point distance with C++
#' @description
#' \code{pointDistance2} performs pythagorus and cbinds all columns from \code{to} to new dists column. It
#' is only defined for one point (\code{from}) to many (\code{to}) points.
#' \code{pointDistance3} performs pythagorus and is to be used internally within \code{distanceFromEachPoint}
#' as an alternative to
#' \code{.pointDistance}, where it does many points (\code{from}) to many (\code{to}) points, one \code{from}
#' point at a time. The results are then rbinded internally. It does not cbind extra columns from \code{to}.
#'
#' @inheritParams distanceFromEachPoint
#' @return
#' \code{pointDistance2} - a matrix with all the \code{to} columns plus one extra \code{dists} column.
#' \code{pointDistance3} - a matrix with x and y columns from \code{to} plus one extra \code{dists} column.
#'
#' @rdname distances
pointDistance2 <- function(to, from) {
    .Call('SpaDES_pointDistance2', PACKAGE = 'SpaDES', to, from)
}

#' @param fromX Numeric vector of x coordinates for 'from' points
#' @param fromY Numeric vector of y coordinates for 'from' points
#' @param toX Numeric vector of x coordinates for 'to' points
#' @param toY Numeric vector of y coordinates for 'to' points
#' @param maxDistance Numeric scalar. The maximum distance cutoff for returned distances.
#' @return
#' A matrix with 3 columns, x0, y0 and dists.
#' @rdname distances
#' @details
#' A slightly faster way to calculate distances.
pointDistance3 <- function(fromX, toX, fromY, toY, maxDistance) {
    .Call('SpaDES_pointDistance3', PACKAGE = 'SpaDES', fromX, toX, fromY, toY, maxDistance)
}

#' @title
#' Rcpp duplicated on integers using Rcpp Sugar
#' @description
#' \code{.duplicatedInt} does same as \code{duplicated} in R, but only on integers, and faster.
#' It uses Rcpp sugar
#'
#' @param x Integer Vector
#' @return
#' A logical vector, as per \code{duplicated}
#'
#' @rdname duplicated
duplicatedInt <- function(x) {
    .Call('SpaDES_duplicatedInt', PACKAGE = 'SpaDES', x)
}

